### PR TITLE
Craft 5

### PR DESCRIPTION
**Pull request by janhenckens**
This makes the few changes needed for Craft 5.
Not sure how you want to handle branching between versions so I made the PR against master for now.

### CODE REVIEW

**Comment by DynamiteGoesBoom** [comment]
Thanks @janhenckens we'll take a look and thank you for the help on this one 🎉 We should be able to get to this later this or next week

**Comment by green17** [comment]
Any update on this? Fantastic plugin. Would love it for Craft 5 too.

**Comment by fdelaneau** [comment]
The scrutinizer error is due to the settings of your test environment not matching Craft 5 requirements.

I’m currently building a site that would greatly benefit from this visual solution instead of a boring menu list, please do the merge :)

**Comment by green17** [comment]
Fantastic thanks for this. :-)

**Pull request merged**
